#!/usr/bin/env python3
"""
Vigil Environment Setup Script
Helps configure .env file for OpenAI API key and other settings
"""

import os
import sys
from pathlib import Path

def setup_env():
    """Set up the .env file with user input"""
    env_file = Path(".env")
    env_example = Path(".env.example")
    
    print(f"\n{'='*60}")
    print(f"👁  Vigil Environment Setup")
    print(f"{'='*60}\n")
    
    # Check if .env already exists
    if env_file.exists():
        print(f"⚠️  .env file already exists")
        response = input("Do you want to overwrite it? (y/N): ").lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    
    # Get OpenAI API key
    print(f"\n📝 OpenAI API Key Setup")
    print(f"Get your key from: https://platform.openai.com/api-keys")
    api_key = input("Enter your OpenAI API key (or press Enter to skip): ").strip()
    
    # Get optional Slack webhook
    print(f"\n📱 Slack Webhook (Optional)")
    print("For sending security alerts to Slack")
    slack_webhook = input("Enter Slack webhook URL (or press Enter to skip): ").strip()
    
    # Create .env file
    env_content = f"""# Vigil Environment Variables
# Generated by setup_env.py

"""
    
    if api_key:
        env_content += f"OPENAI_API_KEY={api_key}\n"
        print(f"✅ OpenAI API key configured")
    else:
        env_content += "# OPENAI_API_KEY=your-openai-api-key-here\n"
        print(f"⚠️  OpenAI API key not set (scan plan generation won't work)")
    
    if slack_webhook:
        env_content += f"\nVIGIL_SLACK_WEBHOOK={slack_webhook}\n"
        print(f"✅ Slack webhook configured")
    else:
        env_content += "\n# VIGIL_SLACK_WEBHOOK=your-slack-webhook-url-here\n"
    
    env_content += f"""
# Optional settings
VIGIL_LOG_LEVEL=INFO
VIGIL_DB_PATH=vigil.db
"""
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ .env file created successfully!")
    print(f"📁 Location: {env_file.absolute()}")
    
    # Show next steps
    print(f"\n🚀 Next Steps:")
    print(f"1. Restart the backend: cd backend && uvicorn main:app --reload")
    print(f"2. Test scan plan generation:")
    print(f"   python3 scan_plan_cli.py https://github.com/owner/repo")
    
    if not api_key:
        print(f"\n⚠️  Note: Without OpenAI API key, scan plan generation won't work")
        print(f"   You can add it later by editing the .env file")
    
    print(f"\n🔐 Security Reminder:")
    print(f"   Never commit .env files to version control")
    print(f"   The .env file is already in .gitignore")


def check_env():
    """Check current environment configuration"""
    env_file = Path(".env")
    
    print(f"\n{'='*60}")
    print(f"👁  Vigil Environment Check")
    print(f"{'='*60}\n")
    
    if not env_file.exists():
        print(f"❌ .env file not found")
        print(f"   Run: python3 setup_env.py")
        return
    
    # Load environment
    from dotenv import load_dotenv
    load_dotenv()
    
    # Check OpenAI API key
    openai_key = os.getenv("OPENAI_API_KEY")
    if openai_key:
        if openai_key.startswith("sk-"):
            print(f"✅ OpenAI API key: Configured")
        else:
            print(f"⚠️  OpenAI API key: Invalid format (should start with 'sk-')")
    else:
        print(f"❌ OpenAI API key: Not configured")
    
    # Check Slack webhook
    slack_webhook = os.getenv("VIGIL_SLACK_WEBHOOK")
    if slack_webhook:
        if slack_webhook.startswith("https://hooks.slack.com"):
            print(f"✅ Slack webhook: Configured")
        else:
            print(f"⚠️  Slack webhook: Invalid format")
    else:
        print(f"ℹ️  Slack webhook: Not configured (optional)")
    
    # Check other settings
    log_level = os.getenv("VIGIL_LOG_LEVEL", "INFO")
    db_path = os.getenv("VIGIL_DB_PATH", "vigil.db")
    print(f"ℹ️  Log level: {log_level}")
    print(f"ℹ️  Database path: {db_path}")
    
    print(f"\n📁 .env file location: {env_file.absolute()}")


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        check_env()
    else:
        setup_env()


if __name__ == "__main__":
    # Check if python-dotenv is available
    try:
        from dotenv import load_dotenv
    except ImportError:
        print("⚠️  python-dotenv not installed")
        print("   Install with: pip3 install python-dotenv")
        sys.exit(1)
    
    main()
